import Button from '@/components/Button';
import { Box, Container, Grid, Typography } from '@mui/material';
import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });
import styles from '@/styles/Home.module.css';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next Lyrid App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Container>
					<Box display="flex" alignItems="center" justifyContent="center" minHeight="100vh">
						<Grid spacing={4} container justify="center" alignItems="center">
							<Grid item xs={12} md={6}>
								<Box marginBottom={4}>
									<Typography color="black.main" fontSize={12} paddingBottom={1}>
										powered by
									</Typography>
									<Image
										width={132}
										height={66}
										src="/Lyrid.png"
										alt="Lyrid image"
										style={{
											boxShadow: 'rgba(100, 100, 111, 0.2) 0px 7px 29px 0px',
											padding: '10px 15px',
											borderRadius: '10px',
										}}
									/>
								</Box>
								<Typography className={inter.className} fontSize={50} fontWeight={600} color="black.dark" maxWidth={450}>
									NEXT LYRID APP{' '}
								</Typography>
								<Typography className={inter.className} color="black.main" fontSize={16} maxWidth={450}>
									is a Next.js starter with an Material UI setup. Fun, easy to edit and absolutely unique ideas for your web
									applications
								</Typography>
								<Grid container spacing={2} paddingY={2} paddingTop={4}>
									<Grid item>
										<Button variant="contained">Login</Button>
									</Grid>
									<Grid item>
										<Button variant="outlined">Register</Button>
									</Grid>
								</Grid>
							</Grid>
							<Grid item xs={12} md={6} display="flex" alignItems="center" justifyContent="center" flexDirection="column">
								<Image width={350} height={230} src="/ss-app.png" alt="app lyrid image" />
								<Typography className={inter.className} color="black.main" fontSize={12} textAlign="center" maxWidth={400}>
									Stop wasting time on manual tasks. Simple tools such as our full-featured API, CLI and Cloud Manager to
									streamline engineering operations.
								</Typography>
							</Grid>
							<Grid item xs={12} display="flex" alignItems="center" justifyContent="center" flexDirection="column">
								<Grid container justify="center" alignItems="center">
									<Grid item xs={12} sm={6} md={4}>
										{' '}
										<a href="/" className={styles.card} target="_blank" rel="noopener noreferrer">
											<h2 className={inter.className}>
												Docs <span>-&gt;</span>
											</h2>
											<p className={inter.className}>Find in-depth information about NEXT LYRID APP features.</p>
										</a>
									</Grid>
									<Grid item xs={12} sm={6} md={4}>
										{' '}
										<a href="https://www.lyrid.io/" className={styles.card} target="_blank" rel="noopener noreferrer">
											<h2 className={inter.className}>
												Learn <span>-&gt;</span>
											</h2>
											<p className={inter.className}>Learn about Lyrid in an interactive course with&nbsp;quizzes!</p>
										</a>
									</Grid>
									<Grid item xs={12} sm={6} md={4}>
										{' '}
										<a href="https://app.lyrid.io/" className={styles.card} target="_blank" rel="noopener noreferrer">
											<h2 className={inter.className}>
												Deploy <span>-&gt;</span>
											</h2>
											<p className={inter.className}>
												Instantly deploy your NEXT LYRID APP site to a shareable URL with&nbsp;Lyrid.
											</p>
										</a>
									</Grid>
								</Grid>
							</Grid>
						</Grid>
					</Box>
				</Container>
			</main>
		</>
	);
}
